export { default as Home } from './Home'
export { default as Subjects } from './Subjects'
export { default as Settings } from './Settings'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Progress } from './Progress'
export { default as Flashcards } from './Flashcards'
export { default as AllQuestions } from './AllQuestions'
